### ISSUE TITLE
Feature request: Nametags and self-avatar setting

### ISSUE THREAD

**Issue by madjin** [exokitxr/multiplayer#19]
It'd be nice to have nametags floating over our avatars so that we can still see each other if we have self-avatar off when screen recording from desktop mode. Lastly, the option to turn nametags on/off will complete the feature set to a gold standard.

**Comment by avaer** [comment]
There is an option to clear your own avatar now.

Still need nametags.

**Comment by avaer** [comment]
Working on nametags here: https://github.com/exokitxr/multiplayer/pull/21

**Comment by avaer** [comment]
Fixed with https://github.com/exokitxr/multiplayer/pull/21.
