### ISSUE TITLE
Quest users cannot change background color

### ISSUE THREAD

**Issue by madjin** [exokitxr/multiplayer#20]
Tested on Oculus browser and Firefox Reality, Quest users cannot change background color and when connected on multiplayer the background colors don't sync (everything else like avatars/objects move/rotate/scale correctly though, cool!)

**Comment by avaer** [comment]
Backgrounds should be settable now, still not synced though.

**Comment by avaer** [comment]
Should be fixed now, including synced for multiplayer.
