### ISSUE TITLE
[Oculus Browser - Go ] Can't re-enter XR mode after back button is pressed 

### ISSUE THREAD

**Issue by kwadroke** [exokitxr/multiplayer#23]
When using Oculus Go, Enter XR Mode, move around, press the back button (which exits XR Mode). Pressing XR Button again does nothing and the page must be reloaded to Enter XR mode again.

Tested on Oculus Go Browser.

**Comment by kwadroke** [comment]
Same result on FF Reality

**Comment by avaer** [comment]
Should be fixed now.
